services:
  dynamodb-local:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    environment:
      - "AWS_ACCESS_KEY_ID=test"
      - "AWS_SECRET_ACCESS_KEY=test"
    command: -jar DynamoDBLocal.jar -sharedDb

  loan-microservice:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - dynamodb-local
    environment:
      - AWS_REGION=us-east-2
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    command: npm start

volumes:
  dynamodb-data:
